window.FOOD_DB = [
  { id:'f01', name:'Poha', serving:'1 bowl (150g)', diet:'veg', region:'west', meal:['breakfast'], cal:250, protein:5, carbs:45, fat:6 },
  { id:'f02', name:'Idli (2 pcs) + Sambar', serving:'2 idli + 1 bowl sambar', diet:'veg', region:'south', meal:['breakfast'], cal:190, protein:7, carbs:35, fat:2 },
  { id:'f03', name:'Masala Dosa', serving:'1 dosa', diet:'veg', region:'south', meal:['breakfast'], cal:350, protein:6, carbs:50, fat:14 },
  { id:'f04', name:'Upma', serving:'1 bowl (150g)', diet:'veg', region:'south', meal:['breakfast'], cal:230, protein:6, carbs:38, fat:7 },
  { id:'f05', name:'Paratha (Aloo) + Curd', serving:'1 paratha + curd', diet:'veg', region:'north', meal:['breakfast'], cal:400, protein:9, carbs:52, fat:17 },
  { id:'f06', name:'Chola Bhatura', serving:'1 plate', diet:'veg', region:'north', meal:['breakfast','lunch'], cal:550, protein:12, carbs:70, fat:24 },
  { id:'f07', name:'Besan Chilla (2 pcs)', serving:'2 chilla', diet:'veg', region:'north', meal:['breakfast'], cal:220, protein:11, carbs:22, fat:9 },
  { id:'f08', name:'Boiled Eggs (2)', serving:'2 eggs', diet:'egg', region:'pan', meal:['breakfast','snack'], cal:155, protein:13, carbs:1, fat:11 },
  { id:'f09', name:'Egg Bhurji (2 eggs)', serving:'2 eggs', diet:'egg', region:'pan', meal:['breakfast'], cal:210, protein:14, carbs:3, fat:16 },
  { id:'f10', name:'Luchi + Aloo Dum', serving:'3 luchi + curry', diet:'veg', region:'east', meal:['breakfast'], cal:420, protein:7, carbs:55, fat:19 },
  { id:'f11', name:'Sattu Paratha', serving:'1 paratha', diet:'veg', region:'east', meal:['breakfast'], cal:310, protein:10, carbs:38, fat:13 },
  { id:'f12', name:'Cornflakes + Milk', serving:'1 bowl', diet:'veg', region:'pan', meal:['breakfast'], cal:200, protein:7, carbs:36, fat:3 },
  { id:'f13', name:'Bread Omelette', serving:'2 slices + 2 eggs', diet:'egg', region:'pan', meal:['breakfast'], cal:320, protein:16, carbs:24, fat:17 },
  { id:'f14', name:'Sprouts Salad', serving:'1 bowl', diet:'veg', region:'pan', meal:['breakfast','snack'], cal:150, protein:9, carbs:22, fat:3 },
  { id:'f15', name:'Peanut Butter Toast (2 slices)', serving:'2 slices', diet:'veg', region:'pan', meal:['breakfast','snack'], cal:290, protein:10, carbs:28, fat:16 },
  { id:'f16', name:'Dal Tadka + Rice', serving:'1 bowl dal + 1 cup rice', diet:'veg', region:'north', meal:['lunch','dinner'], cal:420, protein:14, carbs:70, fat:8 },
  { id:'f17', name:'Rajma Chawal', serving:'1 bowl rajma + 1 cup rice', diet:'veg', region:'north', meal:['lunch','dinner'], cal:480, protein:16, carbs:78, fat:9 },
  { id:'f18', name:'Chole Chawal', serving:'1 bowl chole + 1 cup rice', diet:'veg', region:'north', meal:['lunch','dinner'], cal:460, protein:13, carbs:75, fat:10 },
  { id:'f19', name:'Paneer Butter Masala + Roti (2)', serving:'1 bowl + 2 roti', diet:'veg', region:'north', meal:['lunch','dinner'], cal:560, protein:20, carbs:48, fat:32 },
  { id:'f20', name:'Roti (2) + Mixed Sabzi', serving:'2 roti + 1 bowl sabzi', diet:'veg', region:'north', meal:['lunch','dinner'], cal:340, protein:9, carbs:52, fat:10 },
  { id:'f21', name:'Sambar Rice', serving:'1 plate', diet:'veg', region:'south', meal:['lunch','dinner'], cal:380, protein:10, carbs:68, fat:7 },
  { id:'f22', name:'Curd Rice', serving:'1 bowl', diet:'veg', region:'south', meal:['lunch','dinner'], cal:280, protein:8, carbs:48, fat:6 },
  { id:'f23', name:'Lemon Rice', serving:'1 plate', diet:'veg', region:'south', meal:['lunch','dinner'], cal:320, protein:6, carbs:58, fat:8 },
  { id:'f24', name:'Bisibele Bath', serving:'1 plate', diet:'veg', region:'south', meal:['lunch','dinner'], cal:400, protein:11, carbs:65, fat:10 },
  { id:'f25', name:'Fish Curry + Rice', serving:'1 piece fish + rice', diet:'nonveg', region:'east', meal:['lunch','dinner'], cal:450, protein:26, carbs:60, fat:11 },
  { id:'f26', name:'Chingri Malai Curry + Rice', serving:'1 bowl + rice', diet:'nonveg', region:'east', meal:['lunch','dinner'], cal:480, protein:22, carbs:58, fat:17 },
  { id:'f27', name:'Litti Chokha (2 pcs)', serving:'2 litti + chokha', diet:'veg', region:'east', meal:['lunch','dinner'], cal:420, protein:12, carbs:60, fat:14 },
  { id:'f28', name:'Pav Bhaji', serving:'2 pav + bhaji', diet:'veg', region:'west', meal:['lunch','dinner'], cal:500, protein:11, carbs:65, fat:22 },
  { id:'f29', name:'Dal Baati Churma', serving:'1 plate', diet:'veg', region:'west', meal:['lunch','dinner'], cal:650, protein:14, carbs:85, fat:28 },
  { id:'f30', name:'Undhiyu + Roti', serving:'1 bowl + 2 roti', diet:'veg', region:'west', meal:['lunch','dinner'], cal:400, protein:10, carbs:55, fat:15 },
  { id:'f31', name:'Chicken Curry + Rice', serving:'2 pcs chicken + rice', diet:'nonveg', region:'pan', meal:['lunch','dinner'], cal:520, protein:32, carbs:58, fat:16 },
  { id:'f32', name:'Butter Chicken + Naan', serving:'1 bowl + 1 naan', diet:'nonveg', region:'north', meal:['lunch','dinner'], cal:650, protein:30, carbs:50, fat:36 },
  { id:'f33', name:'Egg Curry + Rice', serving:'2 eggs + rice', diet:'egg', region:'pan', meal:['lunch','dinner'], cal:430, protein:16, carbs:62, fat:12 },
  { id:'f34', name:'Grilled Chicken Breast + Salad', serving:'150g + salad', diet:'nonveg', region:'pan', meal:['lunch','dinner'], cal:320, protein:38, carbs:8, fat:14 },
  { id:'f35', name:'Mutton Curry + Rice', serving:'2 pcs mutton + rice', diet:'nonveg', region:'pan', meal:['lunch','dinner'], cal:580, protein:28, carbs:55, fat:24 },
  { id:'f36', name:'Khichdi + Ghee', serving:'1 bowl', diet:'veg', region:'pan', meal:['lunch','dinner'], cal:350, protein:10, carbs:55, fat:10 },
  { id:'f37', name:'Palak Paneer + Roti (2)', serving:'1 bowl + 2 roti', diet:'veg', region:'north', meal:['lunch','dinner'], cal:480, protein:17, carbs:44, fat:26 },
  { id:'f38', name:'Vegetable Biryani', serving:'1 plate', diet:'veg', region:'south', meal:['lunch','dinner'], cal:420, protein:8, carbs:70, fat:12 },
  { id:'f39', name:'Chicken Biryani', serving:'1 plate', diet:'nonveg', region:'south', meal:['lunch','dinner'], cal:600, protein:28, carbs:75, fat:20 },
  { id:'f40', name:'Egg Biryani', serving:'1 plate', diet:'egg', region:'south', meal:['lunch','dinner'], cal:480, protein:18, carbs:70, fat:15 },
  { id:'f41', name:'Samosa (1 pc)', serving:'1 pc', diet:'veg', region:'north', meal:['snack'], cal:260, protein:4, carbs:28, fat:15 },
  { id:'f42', name:'Dhokla', serving:'4 pcs', diet:'veg', region:'west', meal:['snack'], cal:160, protein:6, carbs:26, fat:4 },
  { id:'f43', name:'Bhel Puri', serving:'1 plate', diet:'veg', region:'west', meal:['snack'], cal:230, protein:5, carbs:42, fat:6 },
  { id:'f44', name:'Roasted Chana (1 cup)', serving:'1 cup', diet:'veg', region:'pan', meal:['snack'], cal:180, protein:10, carbs:28, fat:3 },
  { id:'f45', name:'Mixed Nuts (30g)', serving:'small handful', diet:'veg', region:'pan', meal:['snack'], cal:180, protein:6, carbs:6, fat:16 },
  { id:'f46', name:'Banana', serving:'1 medium', diet:'veg', region:'pan', meal:['snack','breakfast'], cal:105, protein:1, carbs:27, fat:0 },
  { id:'f47', name:'Paneer Tikka (6 pcs)', serving:'6 pcs', diet:'veg', region:'north', meal:['snack'], cal:280, protein:18, carbs:8, fat:20 },
  { id:'f48', name:'Greek Yogurt Bowl', serving:'1 bowl', diet:'veg', region:'pan', meal:['snack','breakfast'], cal:150, protein:15, carbs:12, fat:4 },
  { id:'f49', name:'Muri (Puffed Rice) Chaat', serving:'1 bowl', diet:'veg', region:'east', meal:['snack'], cal:180, protein:4, carbs:35, fat:3 },
  { id:'f50', name:'Protein Shake (whey + milk)', serving:'1 scoop + milk', diet:'veg', region:'pan', meal:['snack'], cal:220, protein:25, carbs:12, fat:6 },
  { id:'f51', name:'Chana Chaat', serving:'1 bowl', diet:'veg', region:'pan', meal:['snack'], cal:200, protein:9, carbs:32, fat:5 },
  { id:'f52', name:'Vada Pav', serving:'1 pc', diet:'veg', region:'west', meal:['snack'], cal:290, protein:6, carbs:40, fat:12 },
  { id:'f53', name:'Curd (1 bowl)', serving:'150g', diet:'veg', region:'pan', meal:['lunch','dinner','snack'], cal:100, protein:6, carbs:8, fat:5 },
  { id:'f54', name:'Ghee (1 tsp)', serving:'1 tsp', diet:'veg', region:'pan', meal:['lunch','dinner'], cal:45, protein:0, carbs:0, fat:5 },
  { id:'f55', name:'Papad (1 pc, roasted)', serving:'1 pc', diet:'veg', region:'pan', meal:['lunch','dinner'], cal:35, protein:2, carbs:6, fat:0.5 },
  { id:'f56', name:'Milk (1 glass)', serving:'250ml', diet:'veg', region:'pan', meal:['breakfast','snack'], cal:150, protein:8, carbs:12, fat:8 },
  { id:'f57', name:'Buttermilk / Chaas', serving:'1 glass', diet:'veg', region:'pan', meal:['lunch','snack'], cal:50, protein:3, carbs:5, fat:2 },
  { id:'f58', name:'Salad (Cucumber-Tomato-Onion)', serving:'1 bowl', diet:'veg', region:'pan', meal:['lunch','dinner'], cal:60, protein:2, carbs:12, fat:0.5 },
  { id:'f59', name:'Plain Roti', serving:'1 roti', diet:'veg', region:'pan', meal:['lunch','dinner'], cal:100, protein:3, carbs:18, fat:1 },
  { id:'f60', name:'Apple', serving:'1 medium', diet:'veg', region:'pan', meal:['snack'], cal:95, protein:0.5, carbs:25, fat:0.3 }
];
